# =========================================
# MYSQL - dung ten service trong docker
# =========================================
spring.datasource.url=jdbc:mysql://mysql:3306/${DB_NAME}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD}
# =========================================
# KAFKA - dung ten service + port noi bo
# =========================================
spring.kafka.bootstrap-servers=kafka:9092

file.upload.path=/app/uploads
file.temp.path=/app/temp

# =========================================
# LOGGING - Logstash trong docker
# =========================================
# (logstash.conf se tu doc tu localhost:5000 ben trong container)